<?php

namespace App\Http\Controllers;

// This base class is normally part of Laravel's own skeleton
// (generated by `composer create-project laravel/laravel`). Our
// scripts/bootstrap-laravel-api.sh deliberately excludes app/ when
// copying the skeleton in, since our app/ already contains the
// controllers/models/middleware we wrote — but that means this one
// framework-provided base class has to live here instead, or every
// controller below (`extends Controller`) would fail to resolve it.
abstract class Controller
{
    //
}
