#!/bin/bash
# ojs/docker-entrypoint.sh
#
# Renders OJS's config.inc.php from environment variables at container
# start (never baked into the image), waits for MySQL to be reachable,
# and then hands off to the container's normal CMD (apache2-foreground).
set -euo pipefail

CONFIG_PATH="/var/www/html/config.inc.php"

: "${OJS_DB_HOST:?OJS_DB_HOST must be set}"
: "${OJS_DB_NAME:?OJS_DB_NAME must be set}"
: "${OJS_DB_USER:?OJS_DB_USER must be set}"
: "${OJS_DB_PASSWORD:?OJS_DB_PASSWORD must be set}"
: "${OJS_BASE_URL:=http://localhost:8080}"

echo "[entrypoint] Waiting for MySQL at ${OJS_DB_HOST}..."
for i in $(seq 1 30); do
  if mysqladmin ping -h"${OJS_DB_HOST}" -u"${OJS_DB_USER}" -p"${OJS_DB_PASSWORD}" --silent 2>/dev/null; then
    echo "[entrypoint] MySQL is reachable."
    break
  fi
  echo "[entrypoint] MySQL not ready yet (attempt ${i}/30)..."
  sleep 2
  if [ "$i" -eq 30 ]; then
    echo "[entrypoint] ERROR: MySQL never became reachable. Exiting." >&2
    exit 1
  fi
done

# Only generate config.inc.php if it doesn't already exist (e.g. on a
# fresh PVC / fresh volume). On restarts against an existing volume we
# leave whatever OJS itself has already written alone.
if [ ! -f "${CONFIG_PATH}" ]; then
  echo "[entrypoint] No existing config.inc.php found — generating one from environment."
  cat > "${CONFIG_PATH}" <<EOF
; Auto-generated by docker-entrypoint.sh at container start.
; Do not edit by hand inside the container — edit environment
; variables in Kubernetes Secrets/ConfigMaps or docker-compose.yml
; instead and recreate the container.
[general]
installed = On
base_url = "${OJS_BASE_URL}"
app_key = "${OJS_APP_KEY:-}"

[database]
driver = mysqli
host = "${OJS_DB_HOST}"
username = "${OJS_DB_USER}"
password = "${OJS_DB_PASSWORD}"
name = "${OJS_DB_NAME}"

[files]
files_dir = /var/www/files

[security]
force_ssl = Off
EOF
  chown www-data:www-data "${CONFIG_PATH}"
  chmod 640 "${CONFIG_PATH}"
  echo "[entrypoint] config.inc.php generated. If this is a first-run, visit ${OJS_BASE_URL}/index.php/index/install to complete OJS's own install wizard."
else
  echo "[entrypoint] Existing config.inc.php found on the volume — leaving it untouched."
fi

exec "$@"
